import { useState, useEffect } from 'react';
import type { ClangFormatStyle, TestingFramework, HooksConfig } from './types';
import { ProjectConfig as ProjectConfigPanel } from './components/ProjectConfig';
import { DependenciesInput } from './components/DependenciesInput';
import { HooksConfig as HooksConfigPanel } from './components/HooksConfig';
import { CLIDownload } from './components/CLIDownload';
import { Documentation } from './components/Documentation';
import { ThemeToggle } from './components/ThemeToggle';
import { useTheme } from './contexts/ThemeContext';

type Tab = 'home' | 'cli' | 'configure' | 'docs';

function App() {
  const { theme } = useTheme();
  const [activeTab, setActiveTab] = useState<Tab>('home');
  const [error, setError] = useState<string | null>(null);

  const [dependencies, setDependencies] = useState<string[]>([]);
  const [cppStandard, setCppStandard] = useState(17);
  const [includeTests, setIncludeTests] = useState(true);
  const [testingFramework, setTestingFramework] = useState<TestingFramework>('googletest');
  const [buildShared, setBuildShared] = useState(false);
  const [clangFormatStyle, setClangFormatStyle] = useState<ClangFormatStyle>('Google');
  const [hooks, setHooks] = useState<HooksConfig>({
    precommit: [],
    prepush: [],
  });

  const [cpxYamlPreview, setCpxYamlPreview] = useState<string>('');

  const generateCpxYaml = () => {
    // Build YAML content
    let yaml = `# cpx.yaml - Generated by Cpx Web UI
# Use with: cpx create <project_name> --template cpx.yaml
# Or: cpx create <project_name> --lib --template cpx.yaml

package:
  version: "0.1.0"
  cpp_standard: ${cppStandard}

build:
  shared_libs: ${buildShared}
  clang_format: "${clangFormatStyle}"
`;

    if (includeTests && testingFramework !== 'none') {
      yaml += `
testing:
  framework: "${testingFramework}"
`;
    }

    if (dependencies.length > 0) {
      yaml += `
dependencies:
`;
      dependencies.forEach((dep) => {
        yaml += `  - ${dep}\n`;
      });
    }

    // Add hooks configuration if any hooks are selected
    if (hooks.precommit.length > 0 || hooks.prepush.length > 0) {
      yaml += `
hooks:
`;
      if (hooks.precommit.length > 0) {
        yaml += `  precommit:
`;
        hooks.precommit.forEach((hook) => {
          yaml += `    - ${hook}\n`;
        });
      }
      if (hooks.prepush.length > 0) {
        yaml += `  prepush:
`;
        hooks.prepush.forEach((hook) => {
          yaml += `    - ${hook}\n`;
        });
      }
    }

    return yaml;
  };

  // Update cpx.yaml preview when config changes
  useEffect(() => {
    const yaml = generateCpxYaml();
    setCpxYamlPreview(yaml);
  }, [cppStandard, dependencies, includeTests, testingFramework, buildShared, clangFormatStyle, hooks]);

  const handleExportYaml = () => {
    const yaml = generateCpxYaml();
    const blob = new Blob([yaml], { type: 'text/yaml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
    a.download = 'cpx.yaml';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
  };


  return (
    <div className={`min-h-screen transition-colors duration-300 ${theme === 'dark' ? 'bg-black' : ''}`} style={theme === 'light' ? { backgroundColor: 'rgb(252, 249, 243)' } : {}}>
      {/* Header */}
      <header className={`border-b backdrop-blur-sm sticky top-0 z-40 ${
        theme === 'dark' 
          ? 'border-white/5 bg-black/20' 
          : 'border-gray-300'
      }`} style={theme === 'light' ? { backgroundColor: 'rgba(252, 249, 243, 0.9)' } : {}}>
        <div className="max-w-7xl mx-auto px-6 py-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-6">
              {/* Logo - clickable to go home */}
              <button 
                onClick={() => setActiveTab('home')}
                className="hover:opacity-80 transition-opacity"
              >
                <img src="/cpx.svg" alt="Cpx" className="w-12 h-12" />
              </button>

              {/* Tabs */}
              <nav className="flex items-center gap-1">
                <button
                  onClick={() => setActiveTab('configure')}
                  className={`px-3 py-1 rounded text-sm font-medium transition-all ${
                    activeTab === 'configure'
                      ? theme === 'dark' ? 'text-white' : 'text-gray-900'
                      : theme === 'dark' ? 'text-gray-400 hover:text-white' : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                    Configure
                </button>
                <button
                  onClick={() => setActiveTab('docs')}
                  className={`px-3 py-1 rounded text-sm font-medium transition-all ${
                    activeTab === 'docs'
                      ? theme === 'dark' ? 'text-white' : 'text-gray-900'
                      : theme === 'dark' ? 'text-gray-400 hover:text-white' : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  Docs
                </button>
              </nav>
            </div>

            {/* Actions */}
            <div className="flex items-center gap-3">
              {/* Theme Toggle */}
              <ThemeToggle />

              {/* Configure tab specific actions */}
            {activeTab === 'configure' && (
                <button
                    onClick={handleExportYaml}
                    className="btn-primary px-4 py-1.5 rounded-lg text-sm font-semibold text-white flex items-center gap-2"
                  >
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                      </svg>
                    Export cpx.yaml
                  </button>
                  )}

              {/* GitHub link */}
              <a
                href="https://github.com/ozacod/cpx"
                target="_blank"
                rel="noopener noreferrer"
                className={`p-2 transition-colors ${
                  theme === 'dark' ? 'text-gray-400 hover:text-white' : 'text-gray-600 hover:text-gray-900'
                }`}
                title="View on GitHub"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
                </svg>
              </a>

              {/* Download button - always visible, goes to CLI tab */}
              <button
                onClick={() => setActiveTab('cli')}
                className="bg-cyan-500 hover:bg-cyan-400 text-black px-4 py-1.5 rounded-lg text-sm font-semibold flex items-center gap-2 transition-colors"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download
                </button>
              </div>
          </div>
        </div>
      </header>

      {/* Error banner */}
      {error && (
        <div className="bg-red-500/10 border-b border-red-500/20 px-6 py-3">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <span className="text-red-400 text-sm">{error}</span>
            <button onClick={() => setError(null)} className="text-red-400 hover:text-white">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      )}

      {/* Main content */}
      {activeTab === 'docs' ? (
        <Documentation />
      ) : (
        <main className="max-w-7xl mx-auto px-6 py-8">
        {activeTab === 'home' && (
          <div className="flex flex-col items-center justify-center min-h-[70vh] animate-fade-in">
            <img src="/cpx.svg" alt="Cpx" className="w-48 h-48 mb-8" />
            <h1 className={`font-display text-5xl font-bold mb-4 ${
              theme === 'dark' ? 'text-white' : 'text-gray-900'
            }`}>cpx</h1>
            <p className={`text-xl mb-12 text-center max-w-xl ${
              theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
            }`}>
              The modern C++ project generator. Build, configure, and manage your C++ projects with ease.
            </p>
            <div className="flex gap-4">
              <button
                onClick={() => setActiveTab('cli')}
                className="bg-cyan-500 hover:bg-cyan-400 text-black px-8 py-3 rounded-lg font-semibold flex items-center gap-2 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download CLI
              </button>
              <button
                onClick={() => setActiveTab('configure')}
                className={`px-8 py-3 rounded-lg font-semibold flex items-center gap-2 transition-colors border ${
                  theme === 'dark'
                    ? 'bg-white/10 hover:bg-white/20 text-white border-white/10'
                    : 'bg-gray-100 hover:bg-gray-200 text-gray-900 border-gray-300'
                }`}
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                Configure Project
              </button>
            </div>
          </div>
        )}

        {activeTab === 'cli' && <CLIDownload />}

        {activeTab === 'configure' && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left column - Configuration */}
            <div className="lg:col-span-2 space-y-4">
              <div className="animate-fade-in">
                <ProjectConfigPanel
                  cppStandard={cppStandard}
                  onCppStandardChange={setCppStandard}
                  includeTests={includeTests}
                  onIncludeTestsChange={setIncludeTests}
                  testingFramework={testingFramework}
                  onTestingFrameworkChange={setTestingFramework}
                  buildShared={buildShared}
                  onBuildSharedChange={setBuildShared}
                  clangFormatStyle={clangFormatStyle}
                  onClangFormatStyleChange={setClangFormatStyle}
                />
              </div>

              <div className="animate-fade-in" style={{ animationDelay: '100ms' }}>
                <DependenciesInput
                  dependencies={dependencies}
                  onChange={setDependencies}
                />
              </div>

              <div className="animate-fade-in" style={{ animationDelay: '150ms' }}>
                <HooksConfigPanel
                  hooks={hooks}
                  onChange={setHooks}
                />
              </div>
            </div>

            {/* Right column - Preview */}
            <div className="space-y-6">
              {/* Cpx YAML Preview */}
              <div className="animate-fade-in" style={{ animationDelay: '200ms' }}>
                <CpxYamlPreviewPanel content={cpxYamlPreview} />
              </div>
            </div>
          </div>
        )}
        </main>
      )}
    </div>
  );
}

// Cpx YAML Preview Panel Component
function CpxYamlPreviewPanel({ content }: { content: string }) {
  const { theme } = useTheme();
  const [expanded, setExpanded] = useState(false);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(content);
  };

  return (
    <div className="card-glass rounded-2xl overflow-hidden">
      <div className={`flex items-center justify-between px-5 py-3 border-b ${
        theme === 'dark' ? 'border-white/10' : 'border-gray-300'
      }`}>
        <div className="flex items-center gap-2">
          <span className="font-mono text-sm text-cyan-400">cpx.yaml</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={copyToClipboard}
            className={`p-2 transition-colors ${
              theme === 'dark' ? 'text-gray-500 hover:text-white' : 'text-gray-600 hover:text-gray-900'
            }`}
            title="Copy to clipboard"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
          </button>
          <button
            onClick={() => setExpanded(!expanded)}
            className={`p-2 transition-colors ${
              theme === 'dark' ? 'text-gray-500 hover:text-white' : 'text-gray-600 hover:text-gray-900'
            }`}
            title={expanded ? 'Collapse' : 'Expand'}
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              {expanded ? (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              )}
            </svg>
          </button>
        </div>
      </div>
      <pre
        className={`code-preview p-5 overflow-x-auto text-sm transition-all ${
          expanded ? 'max-h-[1000px]' : 'max-h-[600px]'
        }`}
      >
        <code className={theme === 'dark' ? 'text-gray-300' : 'text-gray-700'}>
          {content.split('\n').map((line, i) => (
            <div key={i} className="flex">
              <span className={`w-8 text-right pr-4 select-none ${
                theme === 'dark' ? 'text-gray-600' : 'text-gray-400'
              }`}>{i + 1}</span>
              <span className={
                line.startsWith('#') ? 'text-green-400' :
                line.includes('hooks:') || line.includes('precommit:') || line.includes('prepush:') ? 'text-purple-400' :
                line.includes('package:') || line.includes('build:') || line.includes('testing:') || line.includes('dependencies:') ? 'text-cyan-400' :
                line.includes(':') && !line.trim().startsWith('#') ? 'text-yellow-400' :
                ''
              }>
                {line || ' '}
              </span>
            </div>
          ))}
        </code>
      </pre>
    </div>
  );
}


export default App;
